services:
  - type: web
    name: lecturescribe
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
      - key: MONGODB_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
